name: ResourcesWorldResetter
version: '2.3.0-UNRELEASED'
main: com.lozaine.ResourceWorldResetter.ResourceWorldResetter
api-version: '1.21'
depend: [Multiverse-Core]
author: Lozaine
description: A plugin to reset the resources world at regular intervals.

commands:
  resourcegui:
    description: "Open the Resource World Admin GUI"
    usage: "/resourcegui"
    permission: "resourceworldresetter.admin"
    aliases: [rwadmin]

  resetworld:
    description: "Force reset the resource world"
    usage: "/resetworld"
    permission: "resourceworldresetter.admin"

  reloadworldresetter:
    description: "Reload the ResourceWorldResetter plugin"
    usage: "/reloadworldresetter"
    permission: "resourceworldresetter.admin"
